---
# stape 2:
# Add Repo & install tools pkg
 - name: Install Tool
   apt:
     name:
       - mc
       - lynx
 - name: Add key
   apt_key:
     url: https://nginx.org/keys/nginx_signing.key
     url: https://www.dotdeb.org/dotdeb.gpg
 - name: add repo
   apt_repository:
     repo: deb http://nginx.org/packages/debian/ stretch nginx
     repo: deb http://dotdeb.mirror.iphh.net/ stretch all
     filename: WebTools
     state: present
     update_cache: yes
#
# Install pkg
 - name: Install Pak
   apt:
     name: "{{ distro }}"
   vars:
     distro:
       - apache2
       - php
       - php-mysql
       - mysql-server
       - mysql-client
       - python-mysqldb
     state: present
# Nginx not friend Apache, port not chenge

 - name: stop Apache2 to install nginx
   service:
     name: apache2
     state: stopped
 - name: install
   apt:
     name: nginx
     state: present

# Add User for mpm_itk
# Config mpm_itk

# Add groupe
 - name: add groupe site1
   group:
     name: test1
     state: present
 - name: add groupe site2
   group:
     name: test2
     state: present

# Add Users
 - name: add user site1
   user:
     name: user1
     group: test1
     shell: /bin/false
     home: /var/www/S1
 - name: add user site2
   user:
     name: user2
     group: test2
     shell: /bin/false
     home: /var/www/S2

# mkdir
 - name: Create dirictory
   file:
     path: /var/www/S1/test1.local
     state: directory
     owner: user1
     group: test1
# mb mode: 0750?
     mode: 0755
     recurse: yes
 - name: Create dirictory
   file:
     path: /var/www/S2/test2.local
     state: directory
     owner: user2
     group: test2
# mb mode: 0750?
     mode: 0755
     recurse: yes

# Edit hosts
 - name: Edit Hosts file
   shell:
     echo "192.168.13.1     test1.local \n192.168.13.2      test2.local" >> /etc/hosts
