---
- hosts: all
  tasks:
# Test Install
    - name: Install MC
      apt:
        pkg: mc
      become: yes
# Add Key!!! and repo
    - name: add deb apt repository key
      apt_key:
          url: https://nginx.org/keys/nginx_signing.key
          state: present
      become: yes    

    - apt_repository:
    
# Нужно проверить вот это вариант
#  always try to use HTTPS. I'm not sure why the nginx folks don't provide it.
#- apt_key: url=http://nginx.org/keys/nginx_signing.key state=present 
#- apt_repository: repo='deb deb http://nginx.org/packages/mainline/ubuntu/ xenial nginx' state=present filename='nginx' update_cache='yes'
#- apt: name='nginx' state='present' update_cache='yes'

# nginx
        repo: deb http://nginx.org/packages/debian/ stretch nginx
        repo: deb-src http://nginx.org/packages/debian/ stretch nginx
# repo dotdeb
        repo: deb http://dotdeb.mirror.iphh.net/ stable all
        repo: deb-src http://dotdeb.mirror.iphh.net/ stable all
        state: present
        state: present
#        get_url:
#          url: https://nginx.org/keys/nginx_signing.key
#          dest: /tmp
#           shell: apt-key add /tmp/nginx_signing.key
      become: yes
# Или.....

#а может и   file: https://nginx.org/keys/nginx_signing.key
#            state: present
    - name: apt update
      shell: apt-get update
      become: yes

# Install NGINX
    - name: Install NGINX
      apt:
        pkg: nginx
      become: yes
      
# Install AMP???
    - name: Install AMP
      apt:
        pkg: amp
      become: yes
