---
- hosts: all
  tasks:
  # Test Install
    - name: Install MC
      apt:
        name: mc
      become: yes
# Add Key!!! and repo
    - name: add deb apt repository key
      apt_key:
          url: https://nginx.org/keys/nginx_signing.key
          url: https://www.dotdeb.org/dotdeb.gpg
          state: present
      become: yes

    - apt_repository:
# nginx
        repo: deb http://nginx.org/packages/debian/ stretch nginx
        state: present
        filename: nginx
#        repo: deb-src http://nginx.org/packages/debian/ stretch nginx
#         filename: nginx
# repo dotdeb for LAMP
        repo: deb http://dotdeb.mirror.iphh.net/ stretch all
        state: present
        filename: lamp
#        repo: deb-src http://dotdeb.mirror.iphh.net/ stable all
#        filename: lamp
        update_cache: yes
#        get_url:
#          url: https://nginx.org/keys/nginx_signing.key
#          dest: /tmp
#           shell: apt-key add /tmp/nginx_signing.key
      become: yes
# Или.....
#а может и   file: https://nginx.org/keys/nginx_signing.key
#            state: present
# USE "UPDATE_CACHE"!!!!!!
#    - name: apt update
#      shell: apt-get update
#     become: yes
# не сестил, да и нужно ли?

# Install NGINX
    - name: Install NGINX
      apt:
        name: nginx
      become: yes
#_______________________________ 15.08  script Work___________________
# Install Apache
    - name: Install apache2
      apt:
        name: apache2
      become: yes

# Install PHP
    - name: Install PHP
      apt:
         name: "{{ packages }}"
      vars:
        packages:
           - php7.0
           - php7.0-mysql
      become: yes

#_______________________________ 16.08 Work___________________
# Install mysql
    - name: MySQL
      apt:
        name: "{{ pacages }}"
      vars:
          pacages:
          - mysql-server
          - mysql-client
          - python-dev
 #         - libmysqlclient-dev
          - python-mysqldb

    - name: started service
      service:
        name: mysql
        state: started
    - name: add user
      mysql_user:
        name: squlya
        # password hello@123
        password: '*A7881F5BF3549F6BD4B75423845825987E3B518F'
        encrypted: yes
        priv: '*.*:ALL,GRANT'
        state: present
      become: yes
#_______________________________ Work___________________
