---
- hosts: all
  tasks:
  # Test Install
    - name: Install MC
      apt:
        name: "{{ testtool }}"
      vars:
          testtool:
            - mc
            - lynx
#        name: mc
      become: yes
# Add Key!!! and repo
    - name: add deb apt repository key
      apt_key:
          url: https://nginx.org/keys/nginx_signing.key
          url: https://www.dotdeb.org/dotdeb.gpg
          state: present
      become: yes

    - apt_repository:
# nginx
        repo: deb http://nginx.org/packages/debian/ stretch nginx
        state: present
        filename: nginx
#        repo: deb-src http://nginx.org/packages/debian/ stretch nginx
#         filename: nginx
# repo dotdeb for LAMP
        repo: deb http://dotdeb.mirror.iphh.net/ stretch all
        state: present
        filename: lamp
#        repo: deb-src http://dotdeb.mirror.iphh.net/ stable all
#        filename: lamp
        update_cache: yes
#        get_url:
#          url: https://nginx.org/keys/nginx_signing.key
#          dest: /tmp
#           shell: apt-key add /tmp/nginx_signing.key
      become: yes

# Install NGINX
    - name: Install NGINX
      apt:
        name: nginx
      become: yes
#
# Install Apache
    - name: Install apache2
      apt:
        name: apache2
      become: yes
# config apache2
#    - name: Config apache2
#      Shell:
#        sed -i 's/Listen 80/Listen 8080/g' /etc/apache2/ports.config
#      Shell:
#        echo NameVirtualHost *:8080 >> /etc/apache2/ports.config


# Install PHP
    - name: Install PHP
      apt:
         name: "{{ packages }}"
      vars:
        packages:
           - php7.0
           - php7.0-mysql
      become: yes

#
# Install mysql
    - name: MySQL
      apt:
        name: "{{ pacages }}"
      vars:
          pacages:
          - mysql-server
          - mysql-client
          - python-dev
 #         - libmysqlclient-dev
          - python-mysqldb

    - name: started service
      service:
        name: mysql
        state: started
    - name: add user
      mysql_user:
        name: squlya
        # password hello@123
        password: '*A7881F5BF3549F6BD4B75423845825987E3B518F'
        encrypted: yes
        priv: '*.*:ALL,GRANT'
        state: present
      become: yes
    - name: set param
      shell:
        echo "[mysqld] \n \n max_connections = 700" >> /etc/mysql/my.cnf
      shell:
        sed -i 's/memory_limit = 128/memory_limit = 256/g' /etc/php/7.0/apache2/php.ini
      become: yes
