# Task DDOS V 0.1
# Install virtual machine

Vagrant.configure(2) do |config|
  config.vm.box = "4linux/debian9"
  config.vm.hostname = "local"
  config.vm.provider :virtualbox do |v|
# Set RAM_memory
  v.memory = 2048
# Set Number CPU
  v.cpus = 2
  config.vm.network "private_network", ip: "192.168.13.1"
  config.vm.network "private_network", ip: "192.168.13.2"
# config.vm.provision "shell", inline: "echo 192.168.13.1 test1.local >> /etc/hosts"
# config.vm.provision "shell", inline: "echo 192.168.13.2 test2.local >> /etc/hosts"
  config.ssh.insert_key = false
  
  
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
    end
  end
end
