---
# Step 3:
# Config pkg
#

# Config mysql

 - name: startsql
   service:
     name: mysql
     state: started

# Add user pass: hello@123

 - name: add sqlUser
   mysql_user:
     name: squlya
     password: '*A7881F5BF3549F6BD4B75423845825987E3B518F'
     encrypted: yes
     priv: '*.*:ALL,GRANT'
     state: present
 - name: add test1
   mysql_user:
     name: usertest1
     password: '*6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9'
     encrypted: yes
     priv: '*.*:ALL,GRANT'
     state: present
 - name: add test1
   mysql_user:
     name: usertest2
     password: '*6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9'
     encrypted: yes
     priv: '*.*:ALL,GRANT'
     state: present
 - name: Create DB_1
   mysql_db:
     name: test1
     state: present
 - name: Create DB_2
   mysql_db:
     name: test2
     state: present

# Set param config
# Set Mysql
 - name: Set sql
   shell:
     echo "[mysqld] \n \n max_connections = 700" >> /etc/mysql/my.cnf
# Set PHP
 - name: Set php
   shell:
     sed -i 's/memory_limit = 128/memory_limit = 256/g' /etc/php/7.0/apache2/php.ini
# set apache config
#  убрать коммент при первом прогоне. Иначе делает дуюди
 - name: set apache
   shell:
     sed -i 's/Listen 80/Listen 8080/g' /etc/apache2/ports.conf
 - name: set apache_2
   shell:
     echo NameVirtualHost *:8080 >> /etc/apache2/ports.conf
#
# Install and config mpm

 - name: install apache2-mpm mod
   apt:
     name: libapache2-mpm-itk
 - name: Add apache mod
   shell: a2enmod mpm_itk

#
 - name: copy apache default
   template: src=000-default.conf.j2 dest=/etc/apache2/sites-available/000-default.cong
 - name: copy test1 apache
   template: src=test1.local.conf.j2 dest=/etc/apache2/sites-available/test1.local.conf
 - name: copy test2 apache
   template: src=test2.local.conf.j2 dest=/etc/apache2/sites-available/test2.local.conf
 - name: enebl site apache
   shell:
     a2ensite test1.local test2.local
 - name: start apache
   service:
     name: apache2
     state: started
# Set nginx config
 - name: Edit nginx.conf
#  убрать коммент при первом прогоне. Иначе делает дуюди
   shell:
     sed -i '29i\\treset_timedout_connection on;' /etc/nginx/nginx.conf
 - name: Copy to avalile nginx test1
   template: src=test1.local.N.conf.j2 dest=/etc/nginx/sites-available/test1.local.N.conf
 - name: Copy to avalile nginx test2
   template: src=test2.local.N.conf.j2 dest=/etc/nginx/sites-available/test2.local.N.conf
 - name: Create s-link nginx
   shell: ln -s /etc/nginx/sites-available/t* /etc/nginx/sites-enabled/
 - name: Nginx restarted
   service:
     name: nginx
     state: restarted
# Download and Install Wordpress
#  убрать коммент при первом прогоне. Иначе делает дублти
 - name: Download Wordpress
   unarchive:
     src: https://wordpress.org/latest.zip
     dest: /tmp/
     remote_src: yes

 - name: Copy WP file to site1
   shell: cp -r /tmp/wordpress/* /var/www/S1/test1.local/
 - name: Copy WP file to site2
   shell: cp -r /tmp/wordpress/* /var/www/S2/test2.local/
# Copy config File
 - name: Copy WP_1 Config file
   template: src=wp-config.php.1.j2 dest=/var/www/S1/test1.local/wp-config.php
 - name: Copy WP_2 config file
   template: src=wp-config.php.2.j2 dest=/var/www/S2/test2.local/wp-config.php

# Last restart web service
 - name: Apache2 restart
   service:
     name: apache2
     state: restarted
 - name: Nginx restart
   service:
     name: nginx
     state: restarted

...
