---
# Step 3:
# Config pkg
#

# Config mysql

 - name: startsql
   service:
     name: mysql
     state: started

# Add user pass: hello@123

 - name: add sqlUser
   mysql_user:
     name: squlya
     password: '*A7881F5BF3549F6BD4B75423845825987E3B518F'
     encrypted: yes
     priv: '*.*:ALL,GRANT'
     state: present

# Set param config
# Set Mysql
 - name: Set sql
   shell:
     echo "[mysqld] \n \n max_connections = 700" >> /etc/mysql/my.cnf
# Set PHP
 - name: Set php
   shell:
     sed -i 's/memory_limit = 128/memory_limit = 256/g' /etc/php/7.0/apache2/php.ini
# set apache config
#  убрать коммент при первом прогоне. Иначе делает дуюди
# - name: set apache
#   shell:
#     sed -i 's/Listen 80/Listen 8080/g' /etc/apache2/ports.conf
# - name: set apache_2
#   shell:
#     echo NameVirtualHost *:8080 >> /etc/apache2/ports.conf
 - name: copy apache default
   template: src=000-default.conf.j2 dest=/etc/apache2/sites-available/000-default.cong
 - name: copy test1 apache
   template: src=test1.local.conf.j2 dest=/etc/apache2/sites-available/test1.local.conf
 - name: copy test2 apache
   template: src=test2.local.conf.j2 dest=/etc/apache2/sites-available/test2.local.conf
 - name: enebl site apache
   shell:
     a2ensite test1.local test2.local
 - name: restart apache
   service:
     name: apache2
     state: restarted
# Set nginx config
# - name: Edit nginx.conf
#  убрать коммент при первом прогоне. Иначе делает дуюди
#   shell:
#     sed -i '29i\\treset_timedout_connection on;' /etc/nginx/nginx.conf
 - name: Copy nginx test
   template: src=test1.local.N.conf.j2 dest=/etc/nginx/sites-available/test1.local.N.conf
 - name: Copy nginx test2
   template: src=test2.local.N.conf.j2 dest=/etc/nginx/sites-available/test2.local.N.conf
 - name: Nginx restarted
   service:
     name: nginx
     state: restarted
# Download and Install Joomla
#  убрать коммент при первом прогоне. Иначе делает дуюди
# - name: Download Joomla
#   get_url:
#     url: https://github.com/joomla/joomla-cms/releases/download/3.8.12/Joomla_3.8.12-Stable-Full_Package.zip
#     dest: /tmp/
# - name: Unarchive
#   shell:
#     unzip /tmp/Joomla_3.8.12-Stable-Full_Package.zip  -d /tmp/j
# Copy joonla to site
 - name: Unarchive tetst1
   shell:
     unzip /tmp/Joomla_3.8.12-Stable-Full_Package.zip  -d /var/www/test1.local
 - name: Unarchive tetst2
   shell:
     unzip /tmp/Joomla_3.8.12-Stable-Full_Package.zip  -d /var/www/test2.local
# - name: Copy joomla file to site1
#   copy:
#     src: /tmp/j
#     dest: /var/www/test1.local
#     remote_src: yes
# - name: Copy joomla file to site2
#   copy:
#     src: /tmp/j
#     dest: /var/www/test2.local
#     remote_src: yes
