---
# Step 3:
# Config pkg
#

# Config mysql

 - name: startsql
   service:
     name: mysql
     state: started

# Add user pass: hello@123

 - name: add sqlUser
   mysql_user:
     name: squlya
     password: '*A7881F5BF3549F6BD4B75423845825987E3B518F'
     encrypted: yes
     priv: '*.*:ALL,GRANT'
     state: present

# Set param config
# Set Mysql
 - name: Set sql
   shell:
     echo "[mysqld] \n \n max_connections = 700" >> /etc/mysql/my.cnf
# Set PHP
 - name: Set php
   shell:
     sed -i 's/memory_limit = 128/memory_limit = 256/g' /etc/php/7.0/apache2/php.ini
# set apache
 - name: set apache
   shell:
     sed -i 's/Listen 80/Listen 8080/g' /etc/apache2/ports.conf
   shell:
     echo NameVirtualHost *:8080 >> /etc/apache2/ports.conf
# Set nginx
 - name: Edit nginx.conf
   shell:
     sed -i '29i\        reset_timedout_connection on' /etc/nginx/nginx.conf
