---

- hosts: all
  become: yes
  become_method: sudo
  tasks:
# Install Tools
      - name: Install Tools
        apt:
          name: "{{ tools }}"
        tools:
          - mc
          - lynx
# Play exp book
      - roles:
         - install_pkg

#      - roles:
#          - config_pkg
