# Task DDOS V 0.2
# Install virtual machine

Vagrant.configure(2) do |config|
  config.vm.box = "4linux/debian9"
  config.vm.hostname = "local"
# если убрать комменты, прогоняте playbook 2 раза. %) 
#  config.vm.provider :virtualbox do |v|
# Set RAM_memory
#  v.memory = 2048
# Set Number CPU
#  v.cpus = 2
  config.vm.network "private_network", ip: "192.168.13.1"
  config.vm.network "private_network", ip: "192.168.13.2"
  config.ssh.insert_key = false


  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "play_0.2.yml"
  end
end
